name: Data updater

on:
  schedule:
    - cron: '30 11 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      # Scraping data
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X PUT https://covid19-data-akita.herokuapp.com/update

